// The prototype of `platform db compose` (#709): merges `extend model` blocks
// from package slice fragments and app fragments into the models the package
// marks `// @extensible`, and writes PLAIN Prisma files. Plain Node ESM, no
// Prisma runtime dependency: it must run in CI and in the Docker build stage
// before `prisma generate` exists.
//
// Fragment syntax (the ONLY non-Prisma syntax):
//
//   // @extensible            <- a comment run directly above `model User {`
//   model User { ... }        <- package-owned, marked once, by its owner
//
//   extend model User {       <- any fragment, package or app
//     workouts Workout[]      <- ONLY back-relation fields (no `fields:`)
//   }
//
// What the composer refuses (each is a ComposeError with a stable `code`):
//   UNKNOWN_MODEL            extend of a model no fragment declares
//   NOT_EXTENSIBLE           extend of a model its owner did not mark @extensible
//   FIELD_COLLISION          the field name already exists on the model or in an earlier extend
//   EXTEND_SCALAR_FIELD      extend adding a column (that is a deviation, not a back-relation)
//   EXTEND_OWNING_RELATION   extend adding a relation WITH `fields:` (it would add a FK column)
//   EXTEND_BLOCK_ATTRIBUTE   extend containing @@index / @@map / ... (alters the package table)
//   EXTEND_UNKNOWN_TYPE      extend field whose type is no model
//   DUPLICATE_MODEL          one name declared (not extended) in two fragments
//   DUPLICATE_BASE           two fragments declare generator/datasource
//   MALFORMED                a block header or footer that is not `prisma format` shaped

import { isExtensible, parseBlocks, parseBody, renderBlock } from './prisma-blocks.mjs';

export const GENERATED_HEADER = '// GENERATED by platform db compose — do not edit';

export class ComposeError extends Error {
  constructor(code, message) {
    super(`${code}: ${message}`);
    this.name = 'ComposeError';
    this.code = code;
  }
}

const where = (block) => `${block.file}:${block.line}`;

/**
 * @param {{rel: string, text: string, origin: 'package'|'app', source: string}[]} inputs
 *   `rel` is the output file name stem; an app input with rel `base.prisma` replaces the package's.
 * @returns {{files: Map<string,string>, extensible: string[], extensions: {model:string, field:string, from:string}[]}}
 */
export function compose(inputs) {
  const sorted = [...inputs].sort((a, b) => (a.origin === b.origin ? a.rel.localeCompare(b.rel) : a.origin === 'package' ? -1 : 1));
  const parsed = [];
  for (const input of sorted) {
    let p;
    try {
      p = parseBlocks(input.text, input.source);
    } catch (e) {
      throw new ComposeError('MALFORMED', e.message);
    }
    parsed.push({ input, ...p });
  }
  // An app `base.prisma` replaces the package one.
  const appBase = parsed.find((p) => p.input.origin === 'app' && p.input.rel === 'base.prisma');
  const live = appBase ? parsed.filter((p) => !(p.input.origin === 'package' && p.input.rel === 'base.prisma')) : parsed;

  // 1. declarations
  const declared = new Map(); // name -> {block, input}
  let baseSeen = null;
  for (const { input, blocks } of live) {
    for (const b of blocks) {
      if (b.kind === 'generator' || b.kind === 'datasource') {
        const key = b.kind === 'datasource' ? 'datasource' : `generator:${b.name}`; // Prisma allows ONE datasource, many uniquely named generators
        if (declared.has(key)) throw new ComposeError('DUPLICATE_BASE', `${b.kind} "${b.name}" declared at ${where(declared.get(key).block)} and ${where(b)}`);
        declared.set(key, { block: b, input });
        baseSeen = baseSeen ?? input;
        continue;
      }
      if (b.extend) continue;
      const prev = declared.get(b.name);
      if (prev) throw new ComposeError('DUPLICATE_MODEL', `${b.kind} "${b.name}" is declared at ${where(prev.block)} and again at ${where(b)}; use "extend model ${b.name} { ... }" to add back-relations`);
      declared.set(b.name, { block: b, input });
    }
  }

  // 2. extensions
  const modelNames = new Set([...declared.values()].filter((d) => d.block.kind === 'model').map((d) => d.block.name));
  const added = new Map(); // model -> [{lines, source, fields}]
  const fieldOwner = new Map(); // `${model}.${field}` -> source
  for (const [, { block }] of declared) {
    if (block.kind !== 'model') continue;
    for (const f of parseBody(block).fields) fieldOwner.set(`${block.name}.${f.name}`, where(block));
  }
  const extensions = [];
  for (const { input, blocks } of live) {
    for (const b of blocks) {
      if (!b.extend) continue;
      if (b.kind !== 'model') throw new ComposeError('MALFORMED', `${where(b)}: only "extend model" is supported`);
      const target = declared.get(b.name);
      if (!target || target.block.kind !== 'model') {
        throw new ComposeError('UNKNOWN_MODEL', `${where(b)}: extend model ${b.name}: no fragment declares a model named ${b.name}`);
      }
      if (!isExtensible(target.block)) {
        throw new ComposeError(
          'NOT_EXTENSIBLE',
          `${where(b)}: model ${b.name} (declared at ${where(target.block)}) is not marked "// @extensible" by its owner; ask for a seam instead of editing it`,
        );
      }
      const { fields, attrs } = parseBody(b);
      if (attrs.length) throw new ComposeError('EXTEND_BLOCK_ATTRIBUTE', `${where(b)}: extend model ${b.name} may not carry block attributes (${attrs[0].raw.trim()}); they would alter the package's table`);
      const lines = [];
      for (const f of fields) {
        if (!modelNames.has(f.type)) {
          const known = new Set(['String', 'Int', 'BigInt', 'Float', 'Decimal', 'Boolean', 'DateTime', 'Json', 'Bytes']);
          const code = known.has(f.type) || [...declared.values()].some((d) => d.block.kind === 'enum' && d.block.name === f.type) ? 'EXTEND_SCALAR_FIELD' : 'EXTEND_UNKNOWN_TYPE';
          throw new ComposeError(code, `${where(b)}: extend model ${b.name}: field "${f.name}" has type ${f.type}; an extend block may only add back-relation fields (a new column is a declared deviation in platform.lock, not an extension)`);
        }
        if (/fields:\s*\[/.test(f.attrs)) {
          throw new ComposeError('EXTEND_OWNING_RELATION', `${where(b)}: extend model ${b.name}: field "${f.name}" is the owning side of a relation (fields: [...]); it would add a foreign key column to the package's table`);
        }
        const key = `${b.name}.${f.name}`;
        if (fieldOwner.has(key)) throw new ComposeError('FIELD_COLLISION', `${where(b)}: extend model ${b.name}: field "${f.name}" already exists (${fieldOwner.get(key)})`);
        fieldOwner.set(key, where(b));
        extensions.push({ model: b.name, field: f.name, from: input.source });
      }
      // keep the block's own comment lines and field lines verbatim
      for (const l of b.lines.slice(1, -1)) lines.push(l);
      if (!added.has(b.name)) added.set(b.name, []);
      added.get(b.name).push({ lines, source: input.source });
    }
  }

  // 3. output
  const files = new Map();
  for (const { input, blocks } of live) {
    const out = [];
    for (const b of blocks) {
      if (b.extend) continue;
      const copy = { ...b, lines: [...b.lines] };
      const ext = added.get(b.name);
      if (ext && b.kind === 'model') {
        const attrIdx = copy.lines.findIndex((l, i) => i > 0 && l.trim().startsWith('@@'));
        const at = attrIdx === -1 ? copy.lines.length - 1 : attrIdx;
        const insert = [];
        for (const e of ext) {
          insert.push('', `  // composed from ${e.source}`, ...e.lines.filter((l, i, a) => !(l.trim() === '' && (i === 0 || i === a.length - 1))));
        }
        // A blank line between the inserted section and a following block attribute.
        if (attrIdx !== -1) insert.push('');
        copy.lines.splice(at, 0, ...insert);
        // Trim a double blank that can appear before @@ attributes.
        copy.lines = copy.lines.filter((l, i, a) => !(l.trim() === '' && a[i - 1] !== undefined && a[i - 1].trim() === ''));
      }
      out.push(renderBlock(copy));
    }
    if (!out.length) continue; // a fragment of pure `extend` blocks has no output file of its own
    const body = out.join('\n\n').replace(/\n{3,}/g, '\n\n').replace(/^\n+/, '');
    const name = `${input.origin === 'package' ? 'platform' : 'app'}.${input.rel}`;
    files.set(name, `${GENERATED_HEADER}\n// source: ${input.source}\n\n${body}\n`);
  }
  const extensible = [...declared.values()].filter((d) => d.block.kind === 'model' && isExtensible(d.block)).map((d) => d.block.name).sort();
  return { files, extensible, extensions };
}
