// Splits the real single-file schema into per-slice files (Q1) and, for Q2,
// into slice FRAGMENTS where each slice declares its own back-relations on
// models it does not own through `extend model` blocks.

import { parseBlocks, parseBody, renderBlock } from './prisma-blocks.mjs';
import { NAME_TO_SLICE, SLICES } from './slices.mjs';

export const GENERATED_BANNER = '// GENERATED by platform db compose — do not edit';

function joinBlocks(blocks) {
  return `${blocks.map(renderBlock).join('\n\n').replace(/\n{3,}/g, '\n\n').replace(/^\n+/, '')}\n`;
}

/** Plain split: one file per slice + base.prisma. Returns Map<fileName, text>. */
export function splitBySlice(src, { generatorOutput } = {}) {
  const { blocks } = parseBlocks(src, 'schema.prisma');
  const files = new Map();
  const base = blocks.filter((b) => b.kind === 'generator' || b.kind === 'datasource');
  if (generatorOutput) {
    for (const b of base) {
      if (b.kind === 'generator') b.lines.splice(b.lines.length - 1, 0, `  output   = "${generatorOutput}"`);
    }
  }
  // Drop the file banner from the first block's leading text for base.prisma only.
  files.set('base.prisma', joinBlocks(base));
  for (const slice of SLICES) {
    const mine = blocks.filter((b) => NAME_TO_SLICE[b.name] === slice && b.kind !== 'generator' && b.kind !== 'datasource');
    if (mine.length) files.set(`${slice}.prisma`, joinBlocks(mine));
  }
  return files;
}

/**
 * Fragment split. A back-relation field (a relation field WITHOUT `fields:`)
 * that sits on a model of slice A but points at a model of slice B moves into
 * slice B's fragment as `extend model <A's model> { ... }`: the slice that owns
 * the foreign key is the slice that knows about the relation. Returns
 * Map<fileName, text> plus a report of what moved.
 */
export function splitIntoFragments(src, { markExtensible = [], generatorOutput } = {}) {
  const { blocks } = parseBlocks(src, 'schema.prisma');
  const modelNames = new Set(blocks.filter((b) => b.kind === 'model').map((b) => b.name));
  const moves = []; // {from model, to slice, lines[], fields[]}
  const bySlice = new Map(SLICES.map((s) => [s, []]));
  const baseBlocks = blocks.filter((b) => b.kind === 'generator' || b.kind === 'datasource');
  if (generatorOutput) for (const b of baseBlocks) if (b.kind === 'generator') b.lines.splice(b.lines.length - 1, 0, `  output   = "${generatorOutput}"`);

  for (const b of blocks) {
    if (b.kind === 'generator' || b.kind === 'datasource') continue;
    if (b.kind !== 'model') continue;
    const { fields } = parseBody(b);
    const drop = new Set(); // line indexes (in b.lines) to remove
    const perSlice = new Map();
    for (const f of fields) {
      if (!modelNames.has(f.type)) continue;
      if (/fields:\s*\[/.test(f.attrs)) continue; // owning side stays with its model
      const target = NAME_TO_SLICE[f.type];
      if (target === NAME_TO_SLICE[b.name]) continue;
      // The field and the comment lines directly above it (until a blank line or a previous field).
      const chunk = [...f.leading.filter((l) => l.trim() !== ''), f.raw];
      const bodyStart = 1;
      const idx = b.lines.indexOf(f.raw, bodyStart);
      let start = idx;
      while (start - 1 >= bodyStart && b.lines[start - 1].trim().startsWith('//')) start--;
      for (let i = start; i <= idx; i++) drop.add(i);
      if (!perSlice.has(target)) perSlice.set(target, { lines: [], fields: [] });
      perSlice.get(target).lines.push(...b.lines.slice(start, idx + 1));
      perSlice.get(target).fields.push(f.name);
      void chunk;
    }
    if (drop.size) b.lines = b.lines.filter((_, i) => !drop.has(i));
    for (const [slice, { lines, fields: names }] of perSlice) {
      moves.push({ model: b.name, toSlice: slice, fields: names });
      bySlice.get(slice).push({
        kind: 'model',
        extend: true,
        name: b.name,
        leading: '',
        lines: [`extend model ${b.name} {`, ...lines, '}'],
      });
    }
  }

  const files = new Map();
  files.set('base.prisma', joinBlocks(baseBlocks));
  for (const slice of SLICES) {
    const own = blocks.filter((b) => NAME_TO_SLICE[b.name] === slice && b.kind !== 'generator' && b.kind !== 'datasource');
    for (const b of own) {
      if (b.kind === 'model' && markExtensible.includes(b.name) && !/@extensible/.test(b.leading)) {
        b.leading = `${b.leading.replace(/\s+$/, '')}\n// @extensible`.replace(/^\n/, '');
      }
    }
    const all = [...own, ...bySlice.get(slice)];
    if (all.length) files.set(`${slice}.prisma`, joinBlocks(all));
  }
  return { files, moves };
}
