// The telemetry slice's zod schemas and their inferred types (issue #702),
// one module per route group. This barrel is the slice's `schemas.ts` of the
// contract layout (README -> Conventions); constants.ts stays zod-free.

export { TELEMETRY_SETTINGS_CARRIES_NO_SECRET, telemetryInstanceIdSchema, telemetrySettingsSchema } from './settings.js';
export type {
  TelemetrySettings,
  TelemetrySettingsCarriesNoSecret,
} from './settings.js';
export { telemetryConfigResponseSchema, telemetryPublicConfigSchema, updateTelemetryConfigSchema } from './config.js';
export type {
  TelemetryConfigResponse,
  TelemetryPublicConfig,
  UpdateTelemetryConfigInput,
} from './config.js';
export { telemetryStatusSchema, telemetryTableSchema, telemetryTtlSchema } from './status.js';
export type {
  TelemetryStatus,
  TelemetryTable,
  TelemetryTtl,
} from './status.js';
export {
  telemetryColumnSchema,
  telemetryExportRequestSchema,
  telemetryQueryRequestSchema,
  telemetryQueryResultSchema,
  telemetrySchemaColumnSchema,
  telemetrySchemaSchema,
  telemetrySchemaTableSchema,
  telemetrySqlSchema,
} from './query.js';
export type {
  TelemetryColumn,
  TelemetryExportRequest,
  TelemetryQueryRequest,
  TelemetryQueryResult,
  TelemetrySchema,
  TelemetrySchemaColumn,
  TelemetrySchemaTable,
} from './query.js';
export {
  TELEMETRY_CONNECTION_CARRIES_NO_SECRET,
  telemetryAutomaticConnectionValueSchema,
  telemetryConnectionProbeSchema,
  telemetryConnectionResponseSchema,
  telemetryConnectionSkippedSchema,
  telemetryConnectionTestResultSchema,
  telemetryConnectionValueSchema,
  telemetryCredentialStatusSchema,
  telemetryCustomConnectionValueSchema,
  telemetryDatabaseSchema,
  telemetryDeploymentConnectionSchema,
  telemetryHostSchema,
  telemetryIpVersion,
  telemetryOptionalHostSchema,
  telemetryPgPortSchema,
  telemetryUserSchema,
  testTelemetryConnectionSchema,
  updateTelemetryConnectionSchema,
} from './connection.js';
export type {
  TelemetryAutomaticConnectionValue,
  TelemetryConnectionCarriesNoSecret,
  TelemetryConnectionProbe,
  TelemetryConnectionResponse,
  TelemetryConnectionSkipped,
  TelemetryConnectionTestResult,
  TelemetryConnectionValue,
  TelemetryCredentialStatus,
  TelemetryCustomConnectionValue,
  TelemetryDeploymentConnection,
  TestTelemetryConnectionInput,
  UpdateTelemetryConnectionInput,
  UpdateTelemetryConnectionRequest,
} from './connection.js';
export {
  telemetryStackDeploySchema,
  telemetryStackDeployStartedSchema,
  telemetryStackServiceSchema,
  telemetryStackStatusSchema,
} from './stack.js';
export type {
  TelemetryStackDeploy,
  TelemetryStackDeployStarted,
  TelemetryStackService,
  TelemetryStackStatus,
} from './stack.js';
export {
  apiBucketSchema,
  createTelemetryDashboardMetricsQuerySchema,
  createTelemetryDashboardMetricsSchema,
  dashboardEventSchema,
  logsBucketSchema,
  metricCellSchema,
  metricColumnSchema,
  metricGroupIdSchema,
  metricGroupQuerySchema,
  metricPointSchema,
  metricSeriesSchema,
  metricTableSchema,
  refineWindow,
  telemetryDashboardEnvelopeSchema,
  telemetryDashboardEventsQuerySchema,
  telemetryDashboardEventsSchema,
  telemetryDashboardFiltersSchema,
  telemetryDashboardMetricGroupSchema,
  telemetryDashboardMetricGroupsSchema,
  telemetryDashboardMetricsQuerySchema,
  telemetryDashboardMetricsSchema,
  telemetryDashboardQuerySchema,
  telemetryDashboardSummarySchema,
  telemetryDashboardTileSchema,
  telemetryDashboardTimeseriesQuerySchema,
  telemetryDashboardTimeseriesSchema,
  telemetryDashboardTopQuerySchema,
  telemetryDashboardTopSchema,
  telemetryDashboardUnknownRoutesSchema,
  topErrorSchema,
  topRouteSchema,
  unknownRouteSchema,
} from './dashboard.js';
export type {
  DashboardWindowInput,
  MetricGroupId,
  MetricGroupQueryOptions,
  TelemetryDashboardApiBucket,
  TelemetryDashboardEnvelope,
  TelemetryDashboardEvent,
  TelemetryDashboardEvents,
  TelemetryDashboardEventsQuery,
  TelemetryDashboardFilters,
  TelemetryDashboardLogsBucket,
  TelemetryDashboardMetricCell,
  TelemetryDashboardMetricColumn,
  TelemetryDashboardMetricGroup,
  TelemetryDashboardMetricGroups,
  TelemetryDashboardMetricPoint,
  TelemetryDashboardMetricSeries,
  TelemetryDashboardMetricTable,
  TelemetryDashboardMetrics,
  TelemetryDashboardMetricsQuery,
  TelemetryDashboardQuery,
  TelemetryDashboardSummary,
  TelemetryDashboardTile,
  TelemetryDashboardTimeseries,
  TelemetryDashboardTimeseriesQuery,
  TelemetryDashboardTop,
  TelemetryDashboardTopError,
  TelemetryDashboardTopQuery,
  TelemetryDashboardTopRoute,
  TelemetryDashboardUnknownRoute,
  TelemetryDashboardUnknownRoutes,
} from './dashboard.js';
export { telemetryAssistantRequestSchema, telemetryAssistantTurnSchema } from './assistant.js';
export type {
  TelemetryAssistantAnswerEvent,
  TelemetryAssistantEmit,
  TelemetryAssistantErrorEvent,
  TelemetryAssistantEventMap,
  TelemetryAssistantEventName,
  TelemetryAssistantFinding,
  TelemetryAssistantQuery,
  TelemetryAssistantReport,
  TelemetryAssistantRequest,
  TelemetryAssistantStepEvent,
  TelemetryAssistantTurn,
} from './assistant.js';
