// The composer behind `platform db compose` (docs/adr/0002 D2). Plain TypeScript,
// no Prisma dependency: it must run in CI and in a Docker build stage before
// `prisma generate` exists.

import { ComposeError } from './errors.js';
import { isExtensible, parseBlocks, parseBody, renderBlock, type Block } from './parse.js';

/** First line of every generated file. */
export const GENERATED_HEADER = '// GENERATED by platform db compose — do not edit';

/**
 * One fragment handed to {@link composeFragments}.
 *
 * @internal
 */
export interface FragmentInput {
  /** Origin: the package ships it, or the app owns it. */
  origin: 'package' | 'app';
  /** File name inside its directory, for example `identity.prisma`. */
  name: string;
  /** File contents. */
  text: string;
  /** Path to name in errors (default: `<origin>:<name>`). */
  path?: string;
}

/**
 * What a pure composition produced.
 *
 * @internal
 */
export interface FragmentComposition {
  /** Generated files by name (`platform.identity.prisma`, `app.workouts.prisma`). */
  files: Map<string, string>;
  /** Models the package owners marked `// @extensible`, sorted. */
  extensible: string[];
  /** One entry per merged back-relation field. */
  extensions: Array<{ model: string; field: string; from: string }>;
  /** Non-fatal observations. */
  warnings: string[];
}

const SCALARS = new Set(['String', 'Int', 'BigInt', 'Float', 'Decimal', 'Boolean', 'DateTime', 'Json', 'Bytes', 'Unsupported']);

/** Code-unit order: identical on every machine and locale. */
function byName(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

const labelOf = (i: FragmentInput): string => `${i.origin}:${i.name}`;
const pathOf = (i: FragmentInput): string => i.path ?? labelOf(i);

interface Parsed {
  input: FragmentInput;
  blocks: Block[];
  trailing: string;
}

/**
 * Composes fragments held in memory. Package fragments load first, then app
 * fragments, each alphabetically; an app fragment named `base.prisma`
 * replaces the package's. `extend model` blocks are merged into their target
 * before its first `@@` line, under a `// composed from <origin>:<file>`
 * comment. The composer generates nothing of its own: a back-relation is
 * always written by the slice that owns the foreign key.
 *
 * @param inputs - The fragments, in any order.
 * @returns The generated files and what was merged.
 * @throws {@link ComposeError} for every rule of the ADR's rejection table.
 * @internal
 */
export function composeFragments(inputs: readonly FragmentInput[]): FragmentComposition {
  const warnings: string[] = [];
  const sorted = [...inputs].sort((a, b) =>
    a.origin === b.origin ? byName(a.name, b.name) : a.origin === 'package' ? -1 : 1,
  );
  const parsed: Parsed[] = sorted.map((input) => ({ input, ...parseBlocks(input.text, pathOf(input)) }));

  const appBase = parsed.find((p) => p.input.origin === 'app' && p.input.name === 'base.prisma');
  if (appBase && parsed.some((p) => p.input.origin === 'package' && p.input.name === 'base.prisma')) {
    warnings.push(
      `${pathOf(appBase.input)} replaces the package's base.prisma: the generator and datasource blocks are now yours to keep current`,
    );
  }
  const live = appBase
    ? parsed.filter((p) => !(p.input.origin === 'package' && p.input.name === 'base.prisma'))
    : parsed;

  // 1. Declarations.
  const declared = new Map<string, { block: Block; file: string }>();
  for (const { input, blocks } of live) {
    for (const b of blocks) {
      if (b.extend) continue;
      // Prisma allows one datasource and many uniquely named generators.
      const key = b.kind === 'datasource' ? 'datasource' : b.kind === 'generator' ? `generator:${b.name}` : b.name;
      const prev = declared.get(key);
      if (prev) {
        const here = `${pathOf(input)}:${b.line}`;
        const there = `${prev.file}:${prev.block.line}`;
        if (b.kind === 'generator' || b.kind === 'datasource') {
          throw new ComposeError(
            'DUPLICATE_BASE',
            pathOf(input),
            b.line,
            `${b.kind} "${b.name}" is already declared at ${there}; an app replaces the package's generator and datasource by providing its own base.prisma, never a second block`,
          );
        }
        throw new ComposeError(
          'DUPLICATE_MODEL',
          pathOf(input),
          b.line,
          `${b.kind} "${b.name}" is already declared at ${there} (again at ${here}); to add back-relations to a model another fragment owns, write "extend model ${b.name} { ... }"`,
        );
      }
      declared.set(key, { block: b, file: pathOf(input) });
    }
  }
  if (![...declared.keys()].some((k) => k === 'datasource')) {
    warnings.push('no datasource block is declared by any fragment; prisma will refuse the composed schema');
  }

  // 2. Extensions.
  const modelNames = new Set<string>();
  const enumNames = new Set<string>();
  for (const { block } of declared.values()) {
    if (block.kind === 'model') modelNames.add(block.name);
    if (block.kind === 'enum') enumNames.add(block.name);
  }
  const fieldOwner = new Map<string, string>();
  for (const { block, file } of declared.values()) {
    if (block.kind !== 'model') continue;
    for (const f of parseBody(block, file).fields) fieldOwner.set(`${block.name}.${f.name}`, `declared at ${file}:${f.line}`);
  }
  const added = new Map<string, Array<{ source: string; lines: string[] }>>();
  const extensions: FragmentComposition['extensions'] = [];
  for (const { input, blocks } of live) {
    const file = pathOf(input);
    for (const b of blocks) {
      if (!b.extend) continue;
      if (b.kind !== 'model') {
        throw new ComposeError('MALFORMED', file, b.line, `only "extend model" is supported, got "extend ${b.kind} ${b.name}"`);
      }
      const target = declared.get(b.name);
      if (!target || target.block.kind !== 'model') {
        throw new ComposeError('UNKNOWN_MODEL', file, b.line, `extend model ${b.name}: no fragment declares a model named ${b.name}`);
      }
      if (!isExtensible(target.block)) {
        throw new ComposeError(
          'NOT_EXTENSIBLE',
          file,
          b.line,
          `extend model ${b.name}: ${b.name} (declared at ${target.file}:${target.block.line}) is not marked "// @extensible" by its owner; request a seam from the package instead of editing it`,
        );
      }
      const { fields, attrs } = parseBody(b, file);
      const attr = attrs[0];
      if (attr) {
        throw new ComposeError(
          'EXTEND_BLOCK_ATTRIBUTE',
          file,
          attr.line,
          `extend model ${b.name} may not carry block attributes (${attr.raw.trim()}); they would alter the package's table`,
        );
      }
      for (const f of fields) {
        if (!modelNames.has(f.type)) {
          const scalar = SCALARS.has(f.type) || enumNames.has(f.type);
          throw new ComposeError(
            scalar ? 'EXTEND_SCALAR_FIELD' : 'EXTEND_UNKNOWN_TYPE',
            file,
            f.line,
            scalar
              ? `extend model ${b.name}: field "${f.name}" has type ${f.type}; an extend block may only add back-relation fields (a new column is a declared deviation in platform.lock, not an extension)`
              : `extend model ${b.name}: field "${f.name}" has type ${f.type}, which no fragment declares as a model`,
          );
        }
        if (/fields:\s*\[/.test(f.attrs)) {
          throw new ComposeError(
            'EXTEND_OWNING_RELATION',
            file,
            f.line,
            `extend model ${b.name}: field "${f.name}" is the owning side of a relation (fields: [...]); it would add a foreign key column to the package's table`,
          );
        }
        const key = `${b.name}.${f.name}`;
        const prior = fieldOwner.get(key);
        if (prior) {
          throw new ComposeError(
            'FIELD_COLLISION',
            file,
            f.line,
            `extend model ${b.name}: field "${f.name}" already exists on ${b.name} (${prior})`,
          );
        }
        fieldOwner.set(key, `added at ${file}:${f.line}`);
        extensions.push({ model: b.name, field: f.name, from: labelOf(input) });
      }
      // The block's own comment and field lines travel verbatim, together with
      // the comment run directly above the block.
      const above: string[] = [];
      const leading = b.leading.split('\n');
      for (let i = leading.length - 1; i >= 0; i--) {
        const t = (leading[i] as string).trim();
        if (t === '' || !t.startsWith('//')) break;
        above.unshift(`  ${t}`);
      }
      const body = b.lines.slice(1, -1);
      while (body.length && (body[0] as string).trim() === '') body.shift();
      while (body.length && (body[body.length - 1] as string).trim() === '') body.pop();
      const list = added.get(b.name) ?? [];
      list.push({ source: labelOf(input), lines: [...above, ...body] });
      added.set(b.name, list);
    }
  }

  // 3. Output: one file per fragment that declares anything.
  const files = new Map<string, string>();
  for (const { input, blocks, trailing } of live) {
    const out: string[] = [];
    for (const b of blocks) {
      if (b.extend) continue;
      const copy = { leading: b.leading, lines: [...b.lines] };
      const ext = b.kind === 'model' ? added.get(b.name) : undefined;
      if (ext) {
        const attrIdx = copy.lines.findIndex((l, i) => i > 0 && l.trim().startsWith('@@'));
        const at = attrIdx === -1 ? copy.lines.length - 1 : attrIdx;
        const insert: string[] = [];
        for (const e of ext) insert.push('', `  // composed from ${e.source}`, ...e.lines);
        if (attrIdx !== -1) insert.push('');
        copy.lines.splice(at, 0, ...insert);
        copy.lines = copy.lines.filter((l, i, a) => !(l.trim() === '' && i > 0 && (a[i - 1] as string).trim() === ''));
      }
      out.push(renderBlock(copy));
    }
    if (!out.length) continue; // a fragment of pure `extend` blocks has no output file of its own
    if (trailing.trim() !== '') out.push(trailing.replace(/^\n+|\n+$/g, ''));
    const body = out.join('\n\n').replace(/\n{3,}/g, '\n\n').replace(/^\n+/, '');
    files.set(`${input.origin === 'package' ? 'platform' : 'app'}.${input.name}`, `${GENERATED_HEADER}\n// source: ${labelOf(input)}\n\n${body}\n`);
  }
  const extensible = [...declared.values()]
    .filter((d) => d.block.kind === 'model' && isExtensible(d.block))
    .map((d) => d.block.name)
    .sort(byName);
  return { files, extensible, extensions, warnings };
}
