import type { MetricGroupDef } from '../metric-group.registry';
import { HOST_FILTERS, LARGEST_TABLES_MAX_ROWS, T } from '../metric-catalog.helpers';

/**
 * The `database` metric group (the postgresql receiver: connections, size, commits, cache hits).
 * The entries moved verbatim from `metric-catalog.ts` (#680); registered by `../metric-group.manifest.ts`.
 */
export const DATABASE_METRIC_GROUP: MetricGroupDef = {
  id: 'database',
  label: 'Database',
  title: 'Database',
  order: 20,
  description: 'connections, size, commits, rollbacks, deadlocks, cache hit ratio, largest tables',
  families: [
    {
      key: 'dbConnections',
      group: 'database',
      label: 'Connections',
      table: 'postgresql_backends',
      kind: 'gauge',
      unit: 'count',
      requiredColumns: ['instance'],
      seriesAggregate: 'sum',
      bucketAggregate: 'max',
      filters: HOST_FILTERS,
    },
    {
      key: 'dbConnectionMax',
      group: 'database',
      label: 'Max connections',
      table: 'postgresql_connection_max',
      kind: 'gauge',
      unit: 'count',
      requiredColumns: ['instance'],
      seriesAggregate: 'max',
      bucketAggregate: 'max',
      filters: HOST_FILTERS,
      series: false,
    },
    {
      key: 'dbSize',
      group: 'database',
      label: 'Database size',
      table: 'postgresql_db_size_bytes',
      kind: 'gauge',
      unit: 'bytes',
      groupBy: 'postgresql_database_name',
      requiredColumns: ['postgresql_database_name'],
      seriesAggregate: 'max',
      bucketAggregate: 'max',
      filters: HOST_FILTERS,
    },
    {
      key: 'dbCommits',
      group: 'database',
      label: 'Commits',
      table: 'postgresql_commits_total',
      kind: 'counter',
      unit: 'per_s',
      rate: 'per_s',
      requiredColumns: ['postgresql_database_name'],
      filters: HOST_FILTERS,
    },
    {
      key: 'dbRollbacks',
      group: 'database',
      label: 'Rollbacks',
      table: 'postgresql_rollbacks_total',
      kind: 'counter',
      unit: 'per_s',
      rate: 'per_s',
      requiredColumns: ['postgresql_database_name'],
      filters: HOST_FILTERS,
    },
    {
      key: 'dbDeadlocks',
      group: 'database',
      label: 'Deadlocks',
      table: 'postgresql_deadlocks_total',
      kind: 'counter',
      unit: 'count',
      rate: 'count',
      requiredColumns: ['postgresql_database_name'],
      filters: HOST_FILTERS,
    },
    {
      key: 'dbBlocksHit',
      group: 'database',
      label: 'Blocks hit',
      table: 'postgresql_blks_hit_total',
      kind: 'counter',
      unit: 'count',
      rate: 'count',
      requiredColumns: ['postgresql_database_name'],
      filters: HOST_FILTERS,
      tile: false,
      series: false,
    },
    {
      key: 'dbBlocksRead',
      group: 'database',
      label: 'Blocks read',
      table: 'postgresql_blks_read_total',
      kind: 'counter',
      unit: 'count',
      rate: 'count',
      requiredColumns: ['postgresql_database_name'],
      filters: HOST_FILTERS,
      tile: false,
      series: false,
    },
  ],
  ratios: [
    {
      key: 'dbConnectionUtilization',
      group: 'database',
      label: 'Connections used',
      unit: '%',
      numerator: [{ family: 'dbConnections' }],
      denominator: [{ family: 'dbConnectionMax' }],
      scale: 100,
      verdict: { ...T.dbConnectionsPct, direction: 'above' },
    },
    {
      key: 'dbCacheHitRatio',
      group: 'database',
      label: 'Cache hit ratio',
      unit: '%',
      numerator: [{ family: 'dbBlocksHit' }],
      denominator: [{ family: 'dbBlocksRead' }],
      addNumerator: true,
      scale: 100,
    },
  ],
  tables: [
    {
      key: 'largestTables',
      group: 'database',
      label: 'Largest tables',
      keyColumn: 'postgresql_table_name',
      keyLabel: 'Table',
      filters: HOST_FILTERS,
      orderByValue: true,
      maxRows: LARGEST_TABLES_MAX_ROWS,
      parts: [
        {
          column: 'sizeBytes',
          label: 'Size',
          unit: 'bytes',
          table: 'postgresql_table_size_bytes',
          seriesAggregate: 'max',
          over: 'last',
        },
      ],
    },
  ],
};
