import type { MetricGroupDef } from '../metric-group.registry';
import { APP_FILTERS } from '../metric-catalog.helpers';

/**
 * The `nodes` metric group (app.nodes.*: fleet health and per-node vitals).
 * The entries moved verbatim from `metric-catalog.ts` (#680); registered by `../metric-group.manifest.ts`.
 */
export const NODES_METRIC_GROUP: MetricGroupDef = {
  id: 'nodes',
  label: 'Worker nodes',
  title: 'Worker nodes',
  order: 40,
  description: 'fleet health, per-node vitals, job types without an eligible node',
  families: [
    {
      key: 'nodesByHealth',
      group: 'nodes',
      label: 'Worker nodes',
      table: 'app_nodes_count',
      kind: 'gauge',
      unit: 'count',
      groupBy: 'health',
      requiredColumns: ['health', 'status'],
      seriesAggregate: 'sum',
      bucketAggregate: 'max',
      filters: APP_FILTERS,
      tileGroups: ['healthy', 'stale', 'offline'],
    },
    {
      key: 'noEligibleNode',
      group: 'nodes',
      label: 'Job types without an eligible node',
      table: 'app_nodes_types_no_eligible_node',
      kind: 'gauge',
      unit: 'count',
      groupBy: 'job_type',
      requiredColumns: ['job_type'],
      seriesAggregate: 'max',
      bucketAggregate: 'max',
      filters: APP_FILTERS,
      tileAggregate: 'countPositive',
      series: false,
    },
  ],
  tables: [
    {
      key: 'nodes',
      group: 'nodes',
      label: 'Nodes',
      keyColumn: 'node_name',
      keyLabel: 'Node',
      filters: APP_FILTERS,
      parts: [
        {
          column: 'cpuCores',
          label: 'CPU',
          unit: 'cores',
          table: 'app_nodes_cpu_utilization',
          seriesAggregate: 'max',
          over: 'last',
        },
        {
          column: 'rssBytes',
          label: 'RSS',
          unit: 'bytes',
          table: 'app_nodes_memory_rss_bytes',
          seriesAggregate: 'max',
          over: 'last',
        },
        {
          column: 'heapUsedBytes',
          label: 'Heap used',
          unit: 'bytes',
          table: 'app_nodes_heap_used_bytes',
          seriesAggregate: 'max',
          over: 'last',
        },
        {
          column: 'heapLimitBytes',
          label: 'Heap limit',
          unit: 'bytes',
          table: 'app_nodes_heap_limit_bytes',
          seriesAggregate: 'max',
          over: 'last',
        },
        {
          column: 'stateDirFreeBytes',
          label: 'Disk free',
          unit: 'bytes',
          table: 'app_nodes_state_dir_free_bytes',
          seriesAggregate: 'max',
          over: 'last',
        },
        {
          column: 'stateDirTotalBytes',
          label: 'Disk size',
          unit: 'bytes',
          table: 'app_nodes_state_dir_total_bytes',
          seriesAggregate: 'max',
          over: 'last',
        },
        {
          column: 'slotsUsed',
          label: 'Slots used',
          unit: 'count',
          table: 'app_nodes_slots_used',
          seriesAggregate: 'max',
          over: 'last',
        },
        {
          column: 'slotsTotal',
          label: 'Slots',
          unit: 'count',
          table: 'app_nodes_slots_total',
          seriesAggregate: 'max',
          over: 'last',
        },
      ],
      derived: [
        {
          column: 'heapPct',
          label: 'Heap used',
          unit: '%',
          numerator: 'heapUsedBytes',
          denominator: 'heapLimitBytes',
          scale: 100,
        },
        {
          column: 'stateDirFreePct',
          label: 'Disk free',
          unit: '%',
          numerator: 'stateDirFreeBytes',
          denominator: 'stateDirTotalBytes',
          scale: 100,
        },
      ],
    },
    {
      key: 'noEligibleNodeTypes',
      group: 'nodes',
      label: 'Node-offered job types',
      keyColumn: 'job_type',
      keyLabel: 'Job type',
      filters: APP_FILTERS,
      parts: [
        {
          column: 'noEligibleNode',
          label: 'No eligible node',
          unit: 'boolean',
          table: 'app_nodes_types_no_eligible_node',
          seriesAggregate: 'max',
          over: 'last',
        },
      ],
    },
  ],
};
