// `@marinoscar/platform-contract/user-data`: the user-data slice's wire
// shapes (issue #743, PP-9.1): the per-user deletion (`/api/user-data/*`),
// the admin factory reset and organization offboarding. Documented in
// ./README.md. Explicit named exports only.

export {
  FACTORY_RESET_BACKUP_PATH,
  FACTORY_RESET_CONFIRMATION,
  FACTORY_RESET_JOB_TYPE,
  FACTORY_RESET_PERMISSION,
  OFFBOARDING_USER_DISPOSITIONS,
  ORG_OFFBOARD_JOB_TYPE,
  ORG_OFFBOARD_PERMISSION,
  USER_DATA_CONTENT_CONFIRMATION,
  USER_DATA_CONTENT_SCOPE,
  USER_DATA_ERROR_CODES,
  USER_DATA_EVERYTHING_CONFIRMATION,
  USER_DATA_EVERYTHING_SCOPE,
  USER_DATA_JOB_STATUSES,
  USER_DATA_PATHS,
  USER_DATA_PERMISSION,
  USER_DATA_PURGE_JOB_TYPE,
  USER_DATA_SCOPE_LAYERS,
} from './constants.js';
export type { OffboardingUserDisposition, UserDataErrorCode, UserDataJobStatus, UserDataScopeLayer } from './constants.js';
export {
  factoryResetRequestSchema,
  factoryResetResultSchema,
  factoryResetStatusSchema,
  factoryResetSummarySchema,
  offboardingPreconditionResultSchema,
  offboardingUserDispositionSchema,
  orgOffboardingRequestSchema,
  orgOffboardingResultSchema,
  orgOffboardingStatusSchema,
  orgOffboardingSummarySchema,
  userDataCategorySummarySchema,
  userDataDeletionRequestSchema,
  userDataDeletionStatusSchema,
  userDataJobStartedSchema,
  userDataJobStatusSchema,
  userDataPurgeResultSchema,
  userDataScopeLayerSchema,
  userDataScopeSchema,
  userDataSummarySchema,
} from './schemas.js';
export type {
  FactoryResetRequest,
  FactoryResetResult,
  FactoryResetStatus,
  FactoryResetSummary,
  OffboardingPreconditionResult,
  OffboardingUserDispositionEnum,
  OrgOffboardingRequest,
  OrgOffboardingResult,
  OrgOffboardingStatus,
  OrgOffboardingSummary,
  UserDataCategorySummary,
  UserDataDeletionRequest,
  UserDataDeletionStatus,
  UserDataJobStarted,
  UserDataJobStatusEnum,
  UserDataPurgeResult,
  UserDataScope,
  UserDataScopeLayerEnum,
  UserDataSummary,
} from './schemas.js';
