// `@marinoscar/platform-contract/identity`: the identity slice's wire shapes,
// shared by `@marinoscar/platform-api/identity` (its request DTOs wrap these
// schemas) and the web app (types and the sign-in error codes) (issue #727).
// Documented in ./README.md. Explicit named exports only.
//
// constants.ts is zod-free; a consumer that imports only the constants and the
// types (the web app) never bundles schemas.ts or zod (`"sideEffects": false`).

export {
  ASSIGNABLE_ORG_ROLES,
  AUTH_ERROR_CODES,
  DEFAULT_AUTH_ERROR_CODE,
  DEVICE_SESSION_STATUSES,
  DEVICE_TOKEN_ERROR_CODES,
  DEVICE_TOKEN_TYPES,
  DEVICE_USER_CODE_PATTERN,
  ORG_INVITE_STATUSES,
  ORG_MEMBER_STATUSES,
  ORG_SLUG_PATTERN,
  PAT_DURATION_UNITS,
  PAT_LIMITS,
  TENANCY_MODES,
  isAuthErrorCode,
} from './constants.js';
export type {
  AssignableOrgRole,
  AuthErrorCode,
  DeviceSessionStatus,
  DeviceTokenErrorCode,
  DeviceTokenTypeValue,
  OrgInviteStatus,
  OrgMemberStatus,
  PatDurationUnitValue,
  TenancyModeValue,
} from './constants.js';
export {
  activeOrgSchema,
  authErrorCodeSchema,
  authMembershipSchema,
  authProviderSchema,
  authProvidersResponseSchema,
  authRoleSchema,
  createOrgInviteSchema,
  createOrganizationSchema,
  createPatSchema,
  currentUserSchema,
  deviceActivateResponseSchema,
  deviceAuthorizeRequestSchema,
  deviceAuthorizeResponseSchema,
  deviceClientInfoSchema,
  deviceCodeRequestSchema,
  deviceCodeResponseSchema,
  deviceSessionSchema,
  deviceSessionsResponseSchema,
  deviceTokenErrorSchema,
  deviceTokenRequestSchema,
  deviceTokenResponseSchema,
  deviceTokenTypeSchema,
  orgInviteListQuerySchema,
  orgInviteResponseSchema,
  orgMemberListQuerySchema,
  orgMemberResponseSchema,
  organizationListQuerySchema,
  organizationResponseSchema,
  patCreatedResponseSchema,
  patListItemSchema,
  renameOrganizationSchema,
  switchOrgSchema,
  tokenResponseSchema,
  updateOrgMemberSchema,
} from './schemas.js';
export type {
  ActiveOrg,
  AssignableOrgRoleEnum,
  AuthErrorCodeEnum,
  DeviceSessionStatusEnum,
  DeviceTokenErrorCodeEnum,
  DeviceTokenTypeEnum,
  OrgInviteStatusEnum,
  OrgInviteStatusFilterEnum,
  OrgMemberStatusEnum,
  OrgMemberStatusFilterEnum,
  PatDurationUnitEnum,
  TenancyModeEnum,
  AuthMembership,
  AuthProvidersResponse,
  CreateOrgInviteRequest,
  CreateOrganizationRequest,
  CreatePatRequest,
  CurrentUser,
  DeviceActivateResponse,
  DeviceAuthorizeRequest,
  DeviceAuthorizeResponse,
  DeviceClientInfo,
  DeviceCodeRequest,
  DeviceCodeResponse,
  DeviceSession,
  DeviceSessionsResponse,
  DeviceTokenError,
  DeviceTokenRequest,
  DeviceTokenResponse,
  OrgInviteListQuery,
  OrgInviteResponse,
  OrgMemberListQuery,
  OrgMemberResponse,
  OrganizationListQuery,
  OrganizationResponse,
  PatCreatedResponse,
  PatListItem,
  RenameOrganizationRequest,
  SwitchOrgRequest,
  TokenResponse,
  UpdateOrgMemberRequest,
} from './schemas.js';
