// =============================================================================
// The seed's view of the registries, as a committed file (issue #676)
// =============================================================================
//
// The catalog itself is `buildPermissionCatalog()` of
// `@marinoscar/platform-api/core`. This file renders it the way this app
// commits it: the generator (`scripts/generate-permission-catalog.ts`,
// `npm run catalog:permissions --workspace=api`) writes it to
// `prisma/catalog/permissions.json`, which `prisma/seed-data.ts` reads (the
// production image has no `src/`), and `test/prisma/permission-catalog.spec.ts`
// fails when the committed JSON no longer equals it.
// =============================================================================

import { buildPermissionCatalog, type PermissionCatalog } from '@marinoscar/platform-api/core';

import './permission.manifest';

/** The command that regenerates `prisma/catalog/permissions.json`. */
export const PERMISSION_CATALOG_COMMAND = 'npm run catalog:permissions --workspace=api';

/** The committed catalog file, relative to `apps/api`. */
export const PERMISSION_CATALOG_PATH = 'prisma/catalog/permissions.json';

/**
 * Renders a catalog exactly as the committed file holds it: a `$comment`
 * naming the generator, then the catalog, as 2-space JSON with a trailing
 * newline. The generator writes this string and the staleness test compares
 * the committed file to it byte for byte.
 */
export function renderPermissionCatalog(catalog: PermissionCatalog = buildPermissionCatalog()): string {
  const document = {
    $comment: `Generated by ${PERMISSION_CATALOG_COMMAND}. Do not edit.`,
    ...catalog,
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

/**
 * Compares a committed catalog file with what the registries render now.
 *
 * @param committed - the file's contents, or `undefined` when it is missing.
 * @returns `null` when up to date, otherwise the failure message (which names
 *   the regenerate command). Used by `--check` and by the staleness test.
 */
export function checkPermissionCatalog(committed: string | undefined): string | null {
  if (committed === renderPermissionCatalog()) return null;
  return (
    `${PERMISSION_CATALOG_PATH} is ${committed === undefined ? 'missing' : 'stale'}: ` +
    `run ${PERMISSION_CATALOG_COMMAND} and commit the result.`
  );
}
