// =============================================================================
// The seed's view of the registries (issue #676, PP-1.4)
// =============================================================================
//
// A pure function of the role and permission registries. The generator
// (`scripts/generate-permission-catalog.ts`, `npm run catalog:permissions
// --workspace=api`) writes it to `prisma/catalog/permissions.json`, which
// `prisma/seed-data.ts` reads; `test/prisma/permission-catalog.spec.ts` fails
// when the committed JSON no longer equals this function's output.
// =============================================================================

import { permissionRegistry, roleRegistry } from './permission.registry';
import type { PermissionScope } from './permission.types';

/** What `prisma/seed.ts` upserts: roles, permissions and default role grants. */
export interface PermissionCatalog {
  /** Every registered role, in registration order, with its scope (issue #723). */
  roles: Array<{ name: string; description: string; scope: PermissionScope }>;
  /** Every registered permission, in registration order, with its scope (issue #723). */
  permissions: Array<{ name: string; description: string; scope: PermissionScope }>;
  /** Role → permission ids it is granted by default, in permission registration order. Every role has a key. */
  rolePermissions: Record<string, string[]>;
}

/**
 * Builds the seed catalog from the registries as they are now.
 *
 * Import it through `../common/permissions` (which fills the registries first).
 */
export function buildPermissionCatalog(): PermissionCatalog {
  const roles = roleRegistry.list();
  const permissions = permissionRegistry.list();

  const rolePermissions: Record<string, string[]> = {};
  for (const role of roles) rolePermissions[role.id] = [];
  for (const permission of permissions) {
    for (const role of permission.defaultGrants) (rolePermissions[role] ??= []).push(permission.id);
  }

  return {
    roles: roles.map((role) => ({ name: role.id, description: role.description, scope: role.scope })),
    permissions: permissions.map((permission) => ({
      name: permission.id,
      description: permission.description,
      scope: permission.scope,
    })),
    rolePermissions,
  };
}

/** The command that regenerates `prisma/catalog/permissions.json`. */
export const PERMISSION_CATALOG_COMMAND = 'npm run catalog:permissions --workspace=api';

/** The committed catalog file, relative to `apps/api`. */
export const PERMISSION_CATALOG_PATH = 'prisma/catalog/permissions.json';

/**
 * Renders a catalog exactly as the committed file holds it: a `$comment`
 * naming the generator, then the catalog, as 2-space JSON with a trailing
 * newline. The generator writes this string and the staleness test compares
 * the committed file to it byte for byte.
 */
export function renderPermissionCatalog(catalog: PermissionCatalog = buildPermissionCatalog()): string {
  const document = {
    $comment: `Generated by ${PERMISSION_CATALOG_COMMAND}. Do not edit.`,
    ...catalog,
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

/**
 * Compares a committed catalog file with what the registries render now.
 *
 * @param committed - the file's contents, or `undefined` when it is missing.
 * @returns `null` when up to date, otherwise the failure message (which names
 *   the regenerate command). Used by `--check` and by the staleness test.
 */
export function checkPermissionCatalog(committed: string | undefined): string | null {
  if (committed === renderPermissionCatalog()) return null;
  return (
    `${PERMISSION_CATALOG_PATH} is ${committed === undefined ? 'missing' : 'stale'}: ` +
    `run ${PERMISSION_CATALOG_COMMAND} and commit the result.`
  );
}
