import type { MetricGroupDef } from '../metric-group.registry';
import { eq, HOST_FILTERS, HOST_TABLES, T } from '../metric-catalog.helpers';

/**
 * The `host` metric group (hostmetrics: CPU, memory, load, filesystems, disk and network IO).
 * The entries moved verbatim from `metric-catalog.ts` (#680); registered by `../metric-group.manifest.ts`.
 */
export const HOST_METRIC_GROUP: MetricGroupDef = {
  id: 'host',
  label: 'Host',
  title: 'Infrastructure',
  order: 10,
  description: 'CPU, memory, load, filesystems, disk/network IO',
  families: [
    {
      key: 'cpuUtilization',
      group: 'host',
      label: 'CPU utilization',
      table: HOST_TABLES.cpuUtilization,
      kind: 'gauge',
      unit: '%',
      // Busy = 1 - idle, averaged over every CPU (and host, unless filtered).
      valueSql: '1 - "greptime_value"',
      where: [eq('state', 'idle')],
      requiredColumns: ['state', 'cpu', 'host_name'],
      seriesAggregate: 'avg',
      bucketAggregate: 'avg',
      scale: 100,
      filters: HOST_FILTERS,
      tileAggregate: 'max',
    },
    {
      key: 'memoryUtilization',
      group: 'host',
      label: 'Memory utilization',
      table: HOST_TABLES.memoryUtilization,
      kind: 'gauge',
      unit: '%',
      where: [eq('state', 'used')],
      requiredColumns: ['state', 'host_name'],
      seriesAggregate: 'max',
      bucketAggregate: 'max',
      scale: 100,
      filters: HOST_FILTERS,
      tileAggregate: 'max',
      verdict: { ...T.memoryUtilizationPct, direction: 'above' },
    },
    {
      key: 'load1m',
      group: 'host',
      label: 'Load (1 min)',
      table: HOST_TABLES.load1m,
      kind: 'gauge',
      unit: 'load',
      requiredColumns: ['host_name'],
      seriesAggregate: 'max',
      bucketAggregate: 'max',
      filters: HOST_FILTERS,
      tileAggregate: 'max',
    },
    {
      key: 'filesystemUtilization',
      group: 'host',
      label: 'Filesystem utilization',
      table: HOST_TABLES.filesystemUtilization,
      kind: 'gauge',
      unit: '%',
      groupBy: 'mountpoint',
      requiredColumns: ['mountpoint', 'host_name'],
      seriesAggregate: 'max',
      bucketAggregate: 'max',
      scale: 100,
      filters: HOST_FILTERS,
      tileAggregate: 'max',
      verdict: { ...T.diskUtilizationPct, direction: 'above' },
    },
    {
      key: 'diskIo',
      group: 'host',
      label: 'Disk IO',
      table: HOST_TABLES.diskIo,
      kind: 'counter',
      unit: 'bytes/s',
      rate: 'per_s',
      groupBy: 'direction',
      requiredColumns: ['device', 'direction', 'host_name'],
      filters: HOST_FILTERS,
    },
    {
      // The collector container's network namespace, not the host's NICs (§11.2).
      key: 'networkIo',
      group: 'host',
      label: 'Network IO (collector)',
      table: HOST_TABLES.networkIo,
      kind: 'counter',
      unit: 'bytes/s',
      rate: 'per_s',
      groupBy: 'direction',
      requiredColumns: ['device', 'direction', 'host_name'],
      filters: HOST_FILTERS,
    },
  ],
  tables: [
    {
      key: 'filesystems',
      group: 'host',
      label: 'Filesystems',
      keyColumn: 'mountpoint',
      keyLabel: 'Mountpoint',
      filters: HOST_FILTERS,
      parts: [
        {
          column: 'utilizationPct',
          label: 'Used',
          unit: '%',
          table: HOST_TABLES.filesystemUtilization,
          seriesAggregate: 'max',
          over: 'last',
          scale: 100,
        },
        {
          column: 'usedBytes',
          label: 'Used bytes',
          unit: 'bytes',
          table: HOST_TABLES.filesystemUsage,
          requiredColumns: ['state'],
          where: [eq('state', 'used')],
          seriesAggregate: 'max',
          over: 'last',
        },
        {
          column: 'freeBytes',
          label: 'Free bytes',
          unit: 'bytes',
          table: HOST_TABLES.filesystemUsage,
          requiredColumns: ['state'],
          where: [eq('state', 'free')],
          seriesAggregate: 'max',
          over: 'last',
        },
      ],
    },
  ],
};
