import type { MetricGroupDef } from '../metric-group.registry';
import { HOST_FILTERS } from '../metric-catalog.helpers';

/**
 * The `pipeline` metric group (the collector's and GreptimeDB's own counters, and `up`).
 * The entries moved verbatim from `metric-catalog.ts` (#680); registered by `../metric-group.manifest.ts`.
 */
export const PIPELINE_METRIC_GROUP: MetricGroupDef = {
  id: 'pipeline',
  label: 'Telemetry pipeline',
  title: 'Telemetry pipeline',
  order: 60,
  description: 'collector export and queues, GreptimeDB write stalls, scrape targets',
  families: [
    {
      key: 'exporterSent',
      group: 'pipeline',
      label: 'Metric points sent',
      table: 'otelcol_exporter_sent_metric_points_total',
      kind: 'counter',
      unit: 'per_s',
      rate: 'per_s',
      groupBy: 'exporter',
      requiredColumns: ['exporter'],
      filters: HOST_FILTERS,
    },
    {
      key: 'exporterFailed',
      group: 'pipeline',
      label: 'Metric points failed',
      table: 'otelcol_exporter_send_failed_metric_points_total',
      kind: 'counter',
      unit: 'count',
      rate: 'count',
      groupBy: 'exporter',
      requiredColumns: ['exporter'],
      filters: HOST_FILTERS,
    },
    {
      key: 'exporterQueueSize',
      group: 'pipeline',
      label: 'Exporter queue size',
      table: 'otelcol_exporter_queue_size',
      kind: 'gauge',
      unit: 'count',
      groupBy: 'exporter',
      requiredColumns: ['exporter'],
      seriesAggregate: 'max',
      bucketAggregate: 'max',
      filters: HOST_FILTERS,
      tileAggregate: 'max',
    },
    {
      key: 'exporterQueueCapacity',
      group: 'pipeline',
      label: 'Exporter queue capacity',
      table: 'otelcol_exporter_queue_capacity',
      kind: 'gauge',
      unit: 'count',
      groupBy: 'exporter',
      requiredColumns: ['exporter'],
      seriesAggregate: 'max',
      bucketAggregate: 'max',
      filters: HOST_FILTERS,
      tileAggregate: 'max',
      tile: false,
      series: false,
    },
    {
      key: 'receiverRefused',
      group: 'pipeline',
      label: 'Metric points refused',
      table: 'otelcol_receiver_refused_metric_points_total',
      kind: 'counter',
      unit: 'count',
      rate: 'count',
      groupBy: 'receiver',
      requiredColumns: ['receiver'],
      filters: HOST_FILTERS,
    },
    {
      key: 'greptimeWriteStalls',
      group: 'pipeline',
      label: 'GreptimeDB write stalls',
      table: 'greptime_mito_write_stalling_count',
      kind: 'gauge',
      unit: 'count',
      requiredColumns: [],
      seriesAggregate: 'sum',
      bucketAggregate: 'max',
      filters: HOST_FILTERS,
    },
    {
      key: 'scrapeTargetsDown',
      group: 'pipeline',
      label: 'Scrape targets down',
      table: 'up',
      kind: 'gauge',
      unit: 'count',
      // `job` names the scrape target readably (`greptimedb`, `otelcol-contrib`);
      // the collector's own `instance` is its random service instance id.
      groupBy: 'job',
      requiredColumns: ['job'],
      seriesAggregate: 'min',
      bucketAggregate: 'min',
      filters: HOST_FILTERS,
      tileAggregate: 'countZero',
      series: false,
    },
  ],
  ratios: [
    {
      key: 'exporterQueueUtilization',
      group: 'pipeline',
      label: 'Exporter queue used',
      unit: '%',
      numerator: [{ family: 'exporterQueueSize' }],
      denominator: [{ family: 'exporterQueueCapacity' }],
      scale: 100,
    },
  ],
  tables: [
    {
      key: 'scrapeTargets',
      group: 'pipeline',
      label: 'Scrape targets',
      keyColumn: 'job',
      keyLabel: 'Scrape job',
      filters: HOST_FILTERS,
      parts: [
        {
          column: 'up',
          label: 'Up',
          unit: 'boolean',
          table: 'up',
          seriesAggregate: 'min',
          over: 'last',
        },
      ],
    },
  ],
};
