import type { MetricGroupDef } from '../metric-group.registry';
import { APP_FILTERS, eq, T } from '../metric-catalog.helpers';

/**
 * The `queue` metric group (app.jobs.* and app.backup.*: depth, age, settle rate, duration).
 * The entries moved verbatim from `metric-catalog.ts` (#680); registered by `../metric-group.manifest.ts`.
 */
export const QUEUE_METRIC_GROUP: MetricGroupDef = {
  id: 'queue',
  label: 'Job queue',
  title: 'Job queue',
  order: 30,
  description: 'depth, oldest pending job, settle rate, failure ratio, duration p95, last backup, per job type',
  families: [
    {
      key: 'queueDepth',
      group: 'queue',
      label: 'Queue depth',
      table: 'app_jobs_queue_depth',
      kind: 'gauge',
      unit: 'count',
      groupBy: 'status',
      requiredColumns: ['status', 'job_type'],
      seriesAggregate: 'sum',
      bucketAggregate: 'max',
      filters: APP_FILTERS,
      tileGroups: ['pending', 'running'],
    },
    {
      key: 'oldestPendingAge',
      group: 'queue',
      label: 'Oldest pending job',
      table: 'app_jobs_oldest_pending_age_seconds',
      kind: 'gauge',
      unit: 'seconds',
      groupBy: 'job_type',
      requiredColumns: ['job_type'],
      seriesAggregate: 'max',
      bucketAggregate: 'max',
      filters: APP_FILTERS,
      tileAggregate: 'max',
      verdict: {
        degraded: T.oldestPendingJobMinutes.degraded * 60,
        critical: T.oldestPendingJobMinutes.critical * 60,
        direction: 'above',
      },
    },
    {
      key: 'jobsSettled',
      group: 'queue',
      label: 'Jobs settled',
      table: 'app_jobs_settled_total',
      kind: 'counter',
      unit: 'per_min',
      rate: 'per_min',
      groupBy: 'outcome',
      requiredColumns: ['outcome', 'job_type'],
      filters: APP_FILTERS,
    },
    {
      key: 'jobDurationP95',
      group: 'queue',
      label: 'Job duration p95',
      table: 'app_jobs_duration_seconds_bucket',
      kind: 'histogram',
      unit: 'seconds',
      quantile: 0.95,
      groupBy: 'job_type',
      requiredColumns: ['le', 'job_type'],
      filters: APP_FILTERS,
      series: false,
    },
    {
      key: 'backupAge',
      group: 'queue',
      label: 'Last successful backup',
      table: 'app_backup_last_success_timestamp_seconds',
      kind: 'gauge',
      unit: 'hours',
      requiredColumns: [],
      seriesAggregate: 'max',
      bucketAggregate: 'max',
      transform: 'ageHours',
      filters: APP_FILTERS,
      verdict: { ...T.backupAgeHours, direction: 'above' },
    },
  ],
  ratios: [
    {
      key: 'jobFailureRatio',
      group: 'queue',
      label: 'Job failure ratio',
      unit: '%',
      numerator: [{ family: 'jobsSettled', groups: ['failed'] }],
      denominator: [{ family: 'jobsSettled', groups: ['succeeded'] }],
      addNumerator: true,
      scale: 100,
    },
  ],
  tables: [
    {
      key: 'jobTypes',
      group: 'queue',
      label: 'Job types',
      keyColumn: 'job_type',
      keyLabel: 'Job type',
      filters: APP_FILTERS,
      parts: [
        {
          column: 'pending',
          label: 'Pending',
          unit: 'count',
          table: 'app_jobs_queue_depth',
          requiredColumns: ['status'],
          where: [eq('status', 'pending')],
          seriesAggregate: 'max',
          over: 'last',
        },
        {
          column: 'running',
          label: 'Running',
          unit: 'count',
          table: 'app_jobs_queue_depth',
          requiredColumns: ['status'],
          where: [eq('status', 'running')],
          seriesAggregate: 'max',
          over: 'last',
        },
        {
          column: 'oldestPendingSeconds',
          label: 'Oldest pending',
          unit: 'seconds',
          table: 'app_jobs_oldest_pending_age_seconds',
          seriesAggregate: 'max',
          over: 'last',
        },
        {
          column: 'succeeded',
          label: 'Succeeded',
          unit: 'count',
          table: 'app_jobs_settled_total',
          requiredColumns: ['outcome'],
          where: [eq('outcome', 'succeeded')],
          seriesAggregate: 'sum',
          over: 'increase',
        },
        {
          column: 'failed',
          label: 'Failed',
          unit: 'count',
          table: 'app_jobs_settled_total',
          requiredColumns: ['outcome'],
          where: [eq('outcome', 'failed')],
          seriesAggregate: 'sum',
          over: 'increase',
        },
      ],
      histogram: { column: 'durationP95Seconds', label: 'Duration p95', family: 'jobDurationP95' },
    },
  ],
};
