import { defineConfig } from '@prisma/config';

// The schema is a FOLDER generated by `npm run db:compose` (platform
// fragments from @marinoscar/platform-db plus this app's prisma/fragments/).
// `migrations.path` must be explicit with a schema folder.
export default defineConfig({
  schema: 'prisma/schema',
  datasource: { url: process.env.DATABASE_URL as string },
  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node --transpile-only prisma/seed.ts',
  },
});
