// `@marinoscar/platform-contract/notifications`: the notifications slice's
// wire shapes (inbox, events, config, the settings namespaces, Web Push
// configuration, broadcasts), shared by `@marinoscar/platform-api/notifications`
// (its DTOs wrap these schemas) and `@marinoscar/platform-web/notifications`
// (types) (issue #738, PP-8.5). Documented in ./README.md.
// Explicit named exports only. constants.ts is zod-free.

export {
  BROADCAST_BODY_MAX,
  BROADCAST_CHUNK_SIZE,
  BROADCAST_CTA_LABEL_MAX,
  BROADCAST_LINK_MAX,
  BROADCAST_STATUSES,
  BROADCAST_TITLE_MAX,
  DEFAULT_VAPID_SUBJECT,
  MAX_DISABLED_NOTIFICATION_EVENTS,
  NOTIFICATION_CHANNEL_ID_MAX_LENGTH,
  NOTIFICATION_CHANNEL_ID_PATTERN,
  NOTIFICATION_EVENT_KEY_PATTERN,
  NOTIFICATION_MAX_CHANNELS,
  NOTIFICATION_MAX_EVENTS_PER_CHANNEL,
  NOTIFICATION_MAX_EVENT_KEY_LENGTH,
  NOTIFICATION_SSE_EVENT,
  PLATFORM_NOTIFICATION_CHANNEL_IDS,
  PUSH_TEST_CONFIG_SOURCES,
  PUSH_TEST_OVERALL,
  PUSH_TEST_SEND_STATUSES,
  REMOVE_CONFIRMATION,
  ROTATE_CONFIRMATION,
  PUSH_SUBSCRIPTION_PLATFORMS,
  ANDROID_APP_NOTIFICATION_CHANNEL_ID,
} from './constants.js';
export type {
  BroadcastStatusName,
  PlatformNotificationChannelId,
  PushSubscriptionPlatform,
  PushTestConfigSource,
  PushTestOverall,
  PushTestSendStatus,
} from './constants.js';
export {
  PUSH_CONTRACT_CARRIES_NO_SECRET,
  broadcastAudienceQuerySchema,
  broadcastAudienceSchema,
  broadcastCreateResultSchema,
  broadcastDeliveryCountSchema,
  broadcastDetailSchema,
  broadcastListQuerySchema,
  broadcastSchema,
  broadcastTestResultSchema,
  createBroadcastSchema,
  generatePushConfigSchema,
  notificationChannelIdSchema,
  notificationChannelPreferencesPatchSchema,
  notificationChannelPreferencesSchema,
  notificationConfigSchema,
  notificationEventKeySchema,
  notificationEventSchema,
  notificationListQuerySchema,
  notificationSchema,
  notificationStreamEventSchema,
  notificationsPatchSchema,
  notificationsResponseSchema,
  notificationsSchema,
  notificationsSettingsPatchSchema,
  notificationsSettingsSchema,
  orgNotificationsSchema,
  privateKeyStatusSchema,
  pushConfigResponseSchema,
  pushConfigSchema,
  pushSubscribeSchema,
  pushSubscriptionResponseSchema,
  pushTestBrowserDiagnosticsSchema,
  pushTestConfigDiagnosticsSchema,
  pushTestEventDiagnosticsSchema,
  pushTestRequestSchema,
  pushTestResponseSchema,
  pushTestSendResultSchema,
  pushTestSubscriptionResultSchema,
  pushUnsubscribeSchema,
  removePushConfigSchema,
  rotatePushConfigSchema,
  systemNotificationsPatchSchema,
  systemNotificationsSchema,
  unreadCountSchema,
  updatePushConfigSchema,
  vapidSubjectSchema,
} from './schemas.js';
export type {
  BooleanQueryEnum,
  BroadcastStatusEnum,
  NoSecretIn,
  SecretFieldNames,
  PushTestConfigSourceEnum,
  PushTestOverallEnum,
  PushTestSendStatusEnum,
  BroadcastAudienceQuery,
  BroadcastAudienceResponse,
  BroadcastCreateResult,
  BroadcastDetailResponse,
  BroadcastListQuery,
  BroadcastResponse,
  BroadcastTestResult,
  CreateBroadcastInput,
  CreateBroadcastRequest,
  GeneratePushConfigInput,
  NotificationChannelPreferencesValue,
  NotificationConfigResponse,
  NotificationEventResponse,
  NotificationListResponse,
  NotificationResponse,
  NotificationStreamEventPayload,
  NotificationsPatchValue,
  NotificationsValue,
  OrgNotificationsValue,
  PushConfig,
  PushConfigResponse,
  PushContractCarriesNoSecret,
  PushSubscribeRequest,
  PushSubscriptionResponse,
  PushTestBrowserDiagnostics,
  PushTestConfigDiagnostics,
  PushTestEventDiagnostics,
  PushTestRequest,
  PushTestResponse,
  PushTestSendResult,
  PushTestSubscriptionResult,
  PushUnsubscribeRequest,
  RemovePushConfigInput,
  RotatePushConfigInput,
  SystemNotificationsValue,
  UnreadCountResponse,
  UpdatePushConfigInput,
} from './schemas.js';
